localidades_provincias = {
    "Abegondo": "A Coruña",
    "Ames": "A Coruña",
    "Aranga": "A Coruña",
    "Ares": "A Coruña",
    "Arteixo": "A Coruña",
    "Arzúa": "A Coruña",
    "A Baña": "A Coruña",
    "Bergondo": "A Coruña",
    "Betanzos": "A Coruña",
    "Boimorto": "A Coruña",
    "Boiro": "A Coruña",
    "Boqueixón": "A Coruña",
    "Brión": "A Coruña",
    "Cabana De Bergantiños": "A Coruña",
    "Cabanas": "A Coruña",
    "Camariñas": "A Coruña",
    "Cambre": "A Coruña",
    "A Capela": "A Coruña",
    "Carballo": "A Coruña",
    "Carnota": "A Coruña",
    "Carral": "A Coruña",
    "Cedeira": "A Coruña",
    "Cee": "A Coruña",
    "Cerceda": "A Coruña",
    "Cerdido": "A Coruña",
    "Coirós": "A Coruña",
    "Corcubión": "A Coruña",
    "Coristanco": "A Coruña",
    "A Coruña": "A Coruña",
    "Culleredo": "A Coruña",
    "Curtis": "A Coruña",
    "Dodro": "A Coruña",
    "Dumbría": "A Coruña",
    "Fene": "A Coruña",
    "Ferrol": "A Coruña",
    "Fisterra": "A Coruña",
    "Frades": "A Coruña",
    "Irixoa": "A Coruña",
    "Laxe": "A Coruña",
    "A Laracha": "A Coruña",
    "Lousame": "A Coruña",
    "Malpica De Bergantiños": "A Coruña",
    "Mañón": "A Coruña",
    "Mazaricos": "A Coruña",
    "Melide": "A Coruña",
    "Mesía": "A Coruña",
    "Miño": "A Coruña",
    "Moeche": "A Coruña",
    "Monfero": "A Coruña",
    "Mugardos": "A Coruña",
    "Muxía": "A Coruña",
    "Muros": "A Coruña",
    "Narón": "A Coruña",
    "Neda": "A Coruña",
    "Negreira": "A Coruña",
    "Noia": "A Coruña",
    "Oleiros": "A Coruña",
    "Ordes": "A Coruña",
    "Oroso": "A Coruña",
    "Ortigueira": "A Coruña",
    "Outes": "A Coruña",
    "Paderne": "A Coruña",
    "Padrón": "A Coruña",
    "O Pino": "A Coruña",
    "A Pobra Do Caramiñal": "A Coruña",
    "Ponteceso": "A Coruña",
    "Pontedeume": "A Coruña",
    "As Pontes De García Rodríguez": "A Coruña",
    "Porto Do Son": "A Coruña",
    "Rianxo": "A Coruña",
    "Ribeira": "A Coruña",
    "Rois": "A Coruña",
    "Sada": "A Coruña",
    "San Sadurniño": "A Coruña",
    "Santa Comba": "A Coruña",
    "Santiago De Compostela": "A Coruña",
    "Santiso": "A Coruña",
    "Sobrado": "A Coruña",
    "As Somozas": "A Coruña",
    "Teo": "A Coruña",
    "Toques": "A Coruña",
    "Tordoia": "A Coruña",
    "Touro": "A Coruña",
    "Trazo": "A Coruña",
    "Valdoviño": "A Coruña",
    "Val Do Dubra": "A Coruña",
    "Vedra": "A Coruña",
    "Vilasantar": "A Coruña",
    "Vilarmaior": "A Coruña",
    "Vimianzo": "A Coruña",
    "Zas": "A Coruña",
    "Cariño": "A Coruña",
    "Oza-Cesuras": "A Coruña",
    "Abadín": "Lugo",
    "Alfoz": "Lugo",
    "Antas De Ulla": "Lugo",
    "Baleira": "Lugo",
    "Barreiros": "Lugo",
    "Becerreá": "Lugo",
    "Begonte": "Lugo",
    "Bóveda": "Lugo",
    "Carballedo": "Lugo",
    "Castro De Rei": "Lugo",
    "Castroverde": "Lugo",
    "Cervantes": "Lugo",
    "Cervo": "Lugo",
    "O Corgo": "Lugo",
    "Cospeito": "Lugo",
    "Chantada": "Lugo",
    "Folgos Do Courel": "Lugo",
    "A Fonsagrada": "Lugo",
    "Foz": "Lugo",
    "Friol": "Lugo",
    "Xermade": "Lugo",
    "Guitiriz": "Lugo",
    "Guntín": "Lugo",
    "O Incio": "Lugo",
    "Xove": "Lugo",
    "Láncara": "Lugo",
    "Lourenzá": "Lugo",
    "Lugo": "Lugo",
    "Meira": "Lugo",
    "Mondoñedo": "Lugo",
    "Monforte De Lemos": "Lugo",
    "Monterroso": "Lugo",
    "Muras": "Lugo",
    "Navia De Suarna": "Lugo",
    "Negueira De Muñiz": "Lugo",
    "As Nogais": "Lugo",
    "Ourol": "Lugo",
    "Outeiro De Rei": "Lugo",
    "Palas De Rei": "Lugo",
    "Pantón": "Lugo",
    "Paradela": "Lugo",
    "O Páramo": "Lugo",
    "A Pastoriza": "Lugo",
    "Pedrafita Do Cebreiro": "Lugo",
    "Pol": "Lugo",
    "A Pobra Do Brollón": "Lugo",
    "A Pontenova": "Lugo",
    "Portomarín": "Lugo",
    "Quiroga": "Lugo",
    "Ribadeo": "Lugo",
    "Ribas De Sil": "Lugo",
    "Ribeira De Piquín": "Lugo",
    "Riotorto": "Lugo",
    "Samos": "Lugo",
    "Rábade": "Lugo",
    "Sarria": "Lugo",
    "O Saviñao": "Lugo",
    "Sober": "Lugo",
    "Taboada": "Lugo",
    "Trabada": "Lugo",
    "Triacastela": "Lugo",
    "O Valadouro": "Lugo",
    "O Vicedo": "Lugo",
    "Vilalba": "Lugo",
    "Viveiro": "Lugo",
    "Baralla": "Lugo",
    "Burela": "Lugo",
    "Allariz": "Ourense",
    "Amoeiro": "Ourense",
    "A Arnoia": "Ourense",
    "Avión": "Ourense",
    "Baltar": "Ourense",
    "Bande": "Ourense",
    "Baños De Molgas": "Ourense",
    "Barbadás": "Ourense",
    "O Barco De Valdeorras": "Ourense",
    "Beade": "Ourense",
    "Beariz": "Ourense",
    "Os Blancos": "Ourense",
    "Boborás": "Ourense",
    "A Bola": "Ourense",
    "O Bolo": "Ourense",
    "Calvos De Randín": "Ourense",
    "Carballeda De Valdeorras": "Ourense",
    "Carballeda De Avia": "Ourense",
    "O Carballiño": "Ourense",
    "Cartelle": "Ourense",
    "Castrelo Do Val": "Ourense",
    "Castrelo De Miño": "Ourense",
    "Castro Caldelas": "Ourense",
    "Celanova": "Ourense",
    "Cenlle": "Ourense",
    "Coles": "Ourense",
    "Cortegada": "Ourense",
    "Cualedro": "Ourense",
    "Chandrexa De Queixa": "Ourense",
    "Entrimo": "Ourense",
    "Esgos": "Ourense",
    "Xinzo De Limia": "Ourense",
    "Gomesende": "Ourense",
    "A Gudiña": "Ourense",
    "O Irixo": "Ourense",
    "Xunqueira De Ambía": "Ourense",
    "Xunqueira De Espadanedo": "Ourense",
    "Larouco": "Ourense",
    "Laza": "Ourense",
    "Leiro": "Ourense",
    "Lobeira": "Ourense",
    "Lobios": "Ourense",
    "Maceda": "Ourense",
    "Manzaneda": "Ourense",
    "Maside": "Ourense",
    "Melón": "Ourense",
    "A Merca": "Ourense",
    "A Mezquita": "Ourense",
    "Montederramo": "Ourense",
    "Monterrei": "Ourense",
    "Muíños": "Ourense",
    "Nogueira De Ramuín": "Ourense",
    "Oímbra": "Ourense",
    "Ourense": "Ourense",
    "Paderne De Allariz": "Ourense",
    "Padrenda": "Ourense",
    "Parada De Sil": "Ourense",
    "O Pereiro De Aguiar": "Ourense",
    "A Peroxa": "Ourense",
    "Petín": "Ourense",
    "Piñor": "Ourense",
    "Porqueira": "Ourense",
    "A Pobra De Trives": "Ourense",
    "Pontedeva": "Ourense",
    "Punxín": "Ourense",
    "Quintela De Leirado": "Ourense",
    "Rairiz De Veiga": "Ourense",
    "Ramirás": "Ourense",
    "Ribadavia": "Ourense",
    "San Xoán De Río": "Ourense",
    "Riós": "Ourense",
    "A Rúa": "Ourense",
    "Rubiá": "Ourense",
    "San Amaro": "Ourense",
    "San Cibrao Das Viñas": "Ourense",
    "San Cristovo De Cea": "Ourense",
    "Sandiás": "Ourense",
    "Sarreaus": "Ourense",
    "Taboadela": "Ourense",
    "A Teixeira": "Ourense",
    "Toén": "Ourense",
    "Trasmiras": "Ourense",
    "A Veiga": "Ourense",
    "Verea": "Ourense",
    "Verín": "Ourense",
    "Viana Do Bolo": "Ourense",
    "Vilamarín": "Ourense",
    "Vilamartín De Valdeorras": "Ourense",
    "Vilar De Barrio": "Ourense",
    "Vilar De Santos": "Ourense",
    "Vilardevós": "Ourense",
    "Vilariño De Conso": "Ourense",
    "Arbo": "Pontevedra",
    "Barro": "Pontevedra",
    "Baiona": "Pontevedra",
    "Bueu": "Pontevedra",
    "Caldas De Reis": "Pontevedra",
    "Cambados": "Pontevedra",
    "Campo Lameiro": "Pontevedra",
    "Cangas": "Pontevedra",
    "A Cañiza": "Pontevedra",
    "Catoira": "Pontevedra",
    "Covelo": "Pontevedra",
    "Crecente": "Pontevedra",
    "Cuntis": "Pontevedra",
    "Dozón": "Pontevedra",
    "A Estrada": "Pontevedra",
    "Forcarei": "Pontevedra",
    "Fornelos De Montes": "Pontevedra",
    "Agolada": "Pontevedra",
    "Gondomar": "Pontevedra",
    "O Grove": "Pontevedra",
    "A Guarda": "Pontevedra",
    "Lalín": "Pontevedra",
    "A Lama": "Pontevedra",
    "Marín": "Pontevedra",
    "Meaño": "Pontevedra",
    "Meis": "Pontevedra",
    "Moaña": "Pontevedra",
    "Mondariz": "Pontevedra",
    "Mondariz-Balneario": "Pontevedra",
    "Moraña": "Pontevedra",
    "Mos": "Pontevedra",
    "As Neves": "Pontevedra",
    "Nigrán": "Pontevedra",
    "Oia": "Pontevedra",
    "Pazos De Borbén": "Pontevedra",
    "Pontevedra": "Pontevedra",
    "O Porriño": "Pontevedra",
    "Portas": "Pontevedra",
    "Poio": "Pontevedra",
    "Ponteareas": "Pontevedra",
    "Ponte Caldelas": "Pontevedra",
    "Pontecesures": "Pontevedra",
    "Redondela": "Pontevedra",
    "Ribadumia": "Pontevedra",
    "Rodeiro": "Pontevedra",
    "O Rosal": "Pontevedra",
    "Salceda De Caselas": "Pontevedra",
    "Salvaterra De Miño": "Pontevedra",
    "Sanxenxo": "Pontevedra",
    "Silleda": "Pontevedra",
    "Soutomaior": "Pontevedra",
    "Tomiño": "Pontevedra",
    "Tui": "Pontevedra",
    "Valga": "Pontevedra",
    "Vigo": "Pontevedra",
    "Vilaboa": "Pontevedra",
    "Vila De Cruces": "Pontevedra",
    "Vilagarcía De Arousa": "Pontevedra",
    "Vilanova De Arousa": "Pontevedra",
    "A Illa De Arousa": "Pontevedra",
    "Cerdedo-Cotobade": "Pontevedra",
}
